# Sistema
exec-once = systemctl --user start pipewire wireplumber
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# OSD de volumen/brillo
exec-once = swayosd-server

# Portapapeles
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Wallpaper
exec-once = ~/.local/bin/hyprpaper-guard.sh
