source = ~/.config/hypr/env.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/rules.conf

monitor=HDMI-A-1,1920x1080@188,0x0,1

input {
    kb_layout = us,es
    follow_mouse = 1
    sensitivity = 0
}
